# Generated by Django 6.0.2 on 2026-03-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
