# Generated by Django 6.0.2 on 2026-03-01 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_cricao',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 1, 0, 26, 57, 761061)),
        ),
    ]
