# Generated by Django 6.0.2 on 2026-03-01 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_fotografia_data_cricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='data_cricao',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 1, 0, 28, 43, 956794)),
        ),
    ]
