# Generated by Django 6.0.2 on 2026-03-03 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_remove_fotografia_data_cricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 3, 11, 22, 1, 686724)),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
